version: "3"

services:
  #CLIENT
  api-client:
    container_name: api-client
    image: nginx:stable-alpine
    restart: always # always restart unless stopped manually
    ports:
      - 5080:80
    volumes:
      - ../html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apinet

 
#NETWORKS
networks:
  apinet:
    name: apinet
